/**
 * @mainpage HDC Framework Documentation
 *
 * @section intro Introduction
 * This documentation covers the implementation of the Hyperdimensional Computing (HDC) framework 
 * for various use cases including EMG-based movement recognition and custom dataset evaluation. It is based on the work of https://github.com/abbas-rahimi/HDC-EMG
 * This is a reduced version of the project. For the complete version including intermediate results, debugging information and development artifacts refer to https://gitlab.cs.fau.de/ew14ozom/emghandgestureshdc
 * 
 * The framework consists of the following modules:
 * - **Associative Memory (assoc_mem.c)**: Implements storage and retrieval of hypervectors.
 * - **Encoder (encoder.c)**: Encodes input data into hyperdimensional vectors.
 * - **Item Memory (item_mem.c)**: Manages item memory for discrete and continuous signals.
 * - **Operations (operations.c)**: Contains operations such as binding, bundling, and permutation.
 * - **Evaluator (evaluator.c)**: Provides evaluation metrics and classification results.
 * - **Trainer (trainer.c)**: Handles training of the associative memory.
 * - **Preprocessor (preprocessor.c)**: Prepares and downsamples datasets.
 * - **Main Files (e.g., modelCustom.c)**: Entry points for specific use cases.
 *
 * @section usage Usage
 * - Clone the repository and ensure all dependencies are installed.
 * - Configure the project by modifying the appropriate configuration file (e.g., `configCustom.h`).
 * - Compile the project using `make`.
 * - Run the appropriate executable (e.g., `modelCustom`) to train and evaluate the model.
 *
 * @section structure Project Structure
 * - **hdc_infrastructure**: Core framework modules.
 * - **customModel, foot**: Use case-specific implementations and data.
 * - **doc**: Documentation output generated by Doxygen.
 * - **build**: Compiled objects and executables.
 *
 * @section contact Contact
 * For further information, contact:
 * - **Author**: Marian Horn
 * - **Email**: marian.horn@fau.de
 */
