/**
 * @mainpage HDC Framework Documentation
 *
 * @section intro Introduction
 * This documentation covers the implementation of the Hyperdimensional Computing (HDC) framework 
 * for various use cases including EMG-based movement recognition and custom dataset evaluation. It is based on the work of https://github.com/abbas-rahimi/HDC-EMG
 * This version of the project focuses on providing a clean and extensible framework for developing new HDC models. Non-essential components, intermediate results, and debugging artifacts have been omitted for clarity. For a comprehensive version of the project, including all development artifacts, refer to the [FAU GitLab Repository](https://gitlab.cs.fau.de/ew14ozom/emghandgestureshdc).
 * 
 * The framework consists of the following modules:
 * - **Item Memory (item_mem.c)**: Manages the discrete and continuous mappings for features and values into hyperdimensional space.
 * - **Associative Memory (assoc_mem.c)**: Stores and retrieves class hypervectors efficiently.
 * - **Encoder (encoder.c)**: Encodes input data into hyperdimensional vectors.
 * - **Operations (operations.c)**: Provides low-level vector operations, including binding, bundling, and similarity checks.
 * - **Trainer (trainer.c)**: Handles training of the associative memory based on training dataset.
 * - **Evaluator (evaluator.c)**: Evaluates a trained model based on testing dataset.
 * - **Online Classifier (online_classifier.c)**: Evaluates a trained model based on batches of real time incoming test data.
 * - **Preprocessor (preprocessor.c)**: Prepares and downsamples datasets.
 * - **Foot Model (foot/)**: Foot EMG data reader, configuration, and executable model entry point.
 *
 * @section usage Usage
 *
 * @subsection getting_started Getting Started
 * 
 * - Clone the repository:
 *   @code{.bash}
 *   git clone https://gitlab.cs.fau.de/ew14ozom/hdcframeworkhorn
 *   cd hdcframeworkhorn/
 *   @endcode
 *
 * - Build and run the EMG classification model:
 *   @code{.bash}
 *   make foot
 *   ./modelFoot
 *   @endcode
 *
 * - Modify constants in `configFoot.h` to explore parameter effects. After making changes, rebuild and rerun the model.
 *
 * @section structure Project Structure
 * - **hdc_infrastructure**: Core framework modules.
 * - **foot**: Foot EMG use-case implementation and data.
 * - **systemc/synthesis**: SystemC/HLS accelerator implementations.
 * - **doc**: Documentation output generated by Doxygen.
 * - **build**: Compiled objects and executables.
 *
 * @section contact Contact
 * For further information, contact:
 * - **Author**: Marian Horn
 * - **Email**: marian.horn@fau.de
 */
