CC = gcc
CFLAGS = -Wall -Wextra -std=c11 -O3 -march=native -mtune=native -flto -DNDEBUG
LDFLAGS = -lm -flto
CFLAGS += -Ic_model/include

# Optional OpenMP support:
#   USE_OPENMP=1    force enable
#   USE_OPENMP=0    force disable
#   USE_OPENMP=auto enable when compiler supports -fopenmp (default)
USE_OPENMP ?= auto
OPENMP_SUPPORTED := $(shell printf "int main(void){return 0;}\n" | $(CC) -x c -fopenmp -fsyntax-only - >/dev/null 2>&1 && echo 1 || echo 0)
ifeq ($(USE_OPENMP),1)
	CFLAGS += -fopenmp
	LDFLAGS += -fopenmp
else ifeq ($(USE_OPENMP),auto)
ifeq ($(OPENMP_SUPPORTED),1)
	CFLAGS += -fopenmp
	LDFLAGS += -fopenmp
endif
endif

# Optional results CSV path (set RESULT_CSV_PATH=path/to/file.csv)
RESULT_CSV_PATH ?=
ifneq ($(strip $(RESULT_CSV_PATH)),)
	CFLAGS += -DRESULT_CSV_PATH=\"$(RESULT_CSV_PATH)\"
endif
ifdef ITEM_MEM_SEED
	CFLAGS += -DITEM_MEM_SEED=$(ITEM_MEM_SEED)
endif
ifdef DATASET_START
	CFLAGS += -DDATASET_START=$(DATASET_START)
endif
ifdef DATASET_END
	CFLAGS += -DDATASET_END=$(DATASET_END)
endif

# Optional config overrides (set VAR=value)
ifdef VECTOR_DIMENSION
	CFLAGS += -DVECTOR_DIMENSION=$(VECTOR_DIMENSION)
endif
ifdef NUM_LEVELS
	CFLAGS += -DNUM_LEVELS=$(NUM_LEVELS)
endif
ifdef MIN_LEVEL
	CFLAGS += -DMIN_LEVEL=$(MIN_LEVEL)
endif
ifdef MAX_LEVEL
	CFLAGS += -DMAX_LEVEL=$(MAX_LEVEL)
endif
ifdef N_GRAM_SIZE
	CFLAGS += -DN_GRAM_SIZE=$(N_GRAM_SIZE)
endif
ifdef NUM_CLASSES
	CFLAGS += -DNUM_CLASSES=$(NUM_CLASSES)
endif
ifdef NUM_FEATURES
	CFLAGS += -DNUM_FEATURES=$(NUM_FEATURES)
endif
ifdef USE_GENETIC_ITEM_MEMORY
	CFLAGS += -DUSE_GENETIC_ITEM_MEMORY=$(USE_GENETIC_ITEM_MEMORY)
endif
ifdef OUTPUT_MODE
	CFLAGS += -DOUTPUT_MODE=$(OUTPUT_MODE)
endif
ifdef UNIFORM_BINNING
	CFLAGS += -DUNIFORM_BINNING=$(UNIFORM_BINNING)
endif
ifdef QUANTILE_BINNING
	CFLAGS += -DQUANTILE_BINNING=$(QUANTILE_BINNING)
endif
ifdef KMEANS_1D_BINNING
	CFLAGS += -DKMEANS_1D_BINNING=$(KMEANS_1D_BINNING)
endif
ifdef DECISION_TREE_1D_BINNING
	CFLAGS += -DDECISION_TREE_1D_BINNING=$(DECISION_TREE_1D_BINNING)
endif
ifdef CHIMERGE_BINNING
	CFLAGS += -DCHIMERGE_BINNING=$(CHIMERGE_BINNING)
endif
ifdef GA_DEFAULT_POPULATION_SIZE
	CFLAGS += -DGA_DEFAULT_POPULATION_SIZE=$(GA_DEFAULT_POPULATION_SIZE)
endif
ifdef GA_DEFAULT_GENERATIONS
	CFLAGS += -DGA_DEFAULT_GENERATIONS=$(GA_DEFAULT_GENERATIONS)
endif
ifdef GA_DEFAULT_CROSSOVER_RATE
	CFLAGS += -DGA_DEFAULT_CROSSOVER_RATE=$(GA_DEFAULT_CROSSOVER_RATE)
endif
ifdef GA_DEFAULT_MUTATION_RATE
	CFLAGS += -DGA_DEFAULT_MUTATION_RATE=$(GA_DEFAULT_MUTATION_RATE)
endif
ifdef GA_DEFAULT_TOURNAMENT_SIZE
	CFLAGS += -DGA_DEFAULT_TOURNAMENT_SIZE=$(GA_DEFAULT_TOURNAMENT_SIZE)
endif
ifdef GA_DEFAULT_LOG_EVERY
	CFLAGS += -DGA_DEFAULT_LOG_EVERY=$(GA_DEFAULT_LOG_EVERY)
endif
ifdef GA_DEFAULT_SEED
	CFLAGS += -DGA_DEFAULT_SEED=$(GA_DEFAULT_SEED)
endif
ifdef GA_MAX_FLIPS_CIM
	CFLAGS += -DGA_MAX_FLIPS_CIM=$(GA_MAX_FLIPS_CIM)
endif
ifdef BINNING_MODE
	CFLAGS += -DBINNING_MODE=$(BINNING_MODE)
endif
ifdef QUANTIZER_EXPORT_ENABLED
	CFLAGS += -DQUANTIZER_EXPORT_ENABLED=$(QUANTIZER_EXPORT_ENABLED)
endif
ifdef QUANTIZER_EXPORT_CUTS_PATH_TEMPLATE
	CFLAGS += -DQUANTIZER_EXPORT_CUTS_PATH_TEMPLATE=\"$(QUANTIZER_EXPORT_CUTS_PATH_TEMPLATE)\"
endif
ifdef QUANTIZER_EXPORT_CENTERS_PATH_TEMPLATE
	CFLAGS += -DQUANTIZER_EXPORT_CENTERS_PATH_TEMPLATE=\"$(QUANTIZER_EXPORT_CENTERS_PATH_TEMPLATE)\"
endif
ifdef GA_CROSSOVER_ALPHA
	CFLAGS += -DGA_CROSSOVER_ALPHA=$(GA_CROSSOVER_ALPHA)
endif
ifdef GA_CROSSOVER_CHUNK_WIDTH
	CFLAGS += -DGA_CROSSOVER_CHUNK_WIDTH=$(GA_CROSSOVER_CHUNK_WIDTH)
endif
ifdef GA_MUTATION_BETA
	CFLAGS += -DGA_MUTATION_BETA=$(GA_MUTATION_BETA)
endif
ifdef GA_CIM_EXPORT_ENABLED
	CFLAGS += -DGA_CIM_EXPORT_ENABLED=$(GA_CIM_EXPORT_ENABLED)
endif
ifdef GA_CIM_EXPORT_LABEL
	CFLAGS += -DGA_CIM_EXPORT_LABEL=\"$(GA_CIM_EXPORT_LABEL)\"
endif
ifdef VALIDATION_RATIO
	CFLAGS += -DVALIDATION_RATIO=$(VALIDATION_RATIO)
endif

# Directories
SRCDIR = c_model/src
INCDIR = c_model/include
TOOLSDIR = c_model/tools
BINDIR = c_model/build

# C model sources and headers
SRCFILES = $(wildcard $(SRCDIR)/*.c)
OBJFILES = $(patsubst $(SRCDIR)/%.c,$(BINDIR)/%.o,$(SRCFILES))
DEPS = $(wildcard $(INCDIR)/*.h)

# Targets
TARGET_FOOT = $(BINDIR)/hdc_model
TARGET_EXPORT_NAIVE_CIM = $(BINDIR)/export_naive_precomp_cim
TARGET_EVALUATE_FINAL_CIMS = $(BINDIR)/evaluate_final_generation_cims

# Build foot EMG model
.PHONY: foot
foot: clean $(TARGET_FOOT)

$(TARGET_FOOT): $(OBJFILES)
	$(CC) $(CFLAGS) -o $@ $^ $(LDFLAGS)

.PHONY: export_naive_cim
export_naive_cim: clean $(TARGET_EXPORT_NAIVE_CIM)

$(TARGET_EXPORT_NAIVE_CIM): $(TOOLSDIR)/export_naive_precomp_cim.c $(SRCDIR)/item_mem.c $(SRCDIR)/vector.c $(DEPS)
	@mkdir -p $(BINDIR)
	$(CC) $(CFLAGS) -o $@ $(TOOLSDIR)/export_naive_precomp_cim.c $(SRCDIR)/item_mem.c $(SRCDIR)/vector.c $(LDFLAGS)

.PHONY: evaluate_final_cims
evaluate_final_cims: $(TARGET_EVALUATE_FINAL_CIMS)

$(TARGET_EVALUATE_FINAL_CIMS): $(TOOLSDIR)/evaluate_final_generation_cims.c $(filter-out $(SRCDIR)/main.c $(SRCDIR)/ResultManager.c $(SRCDIR)/asymItemMemory.c,$(SRCFILES)) $(DEPS)
	@mkdir -p $(BINDIR)
	$(CC) $(CFLAGS) -o $@ $(TOOLSDIR)/evaluate_final_generation_cims.c $(filter-out $(SRCDIR)/main.c $(SRCDIR)/ResultManager.c $(SRCDIR)/asymItemMemory.c,$(SRCFILES)) $(LDFLAGS)

# Object file compilation
$(BINDIR)/%.o: $(SRCDIR)/%.c $(DEPS)
	@mkdir -p $(BINDIR)
	$(CC) $(CFLAGS) -c -o $@ $<

.PHONY: clean
clean:
	rm -f $(BINDIR)/*.o $(TARGET_FOOT) $(TARGET_EXPORT_NAIVE_CIM) $(TARGET_EVALUATE_FINAL_CIMS)
