#!/usr/bin/env python3
"""Generate a Stratus-friendly packed CiM ROM header from SystemC CiM text.

The input format is the existing systemc_accelerator/partially_parallelized/import/cim_datasetXX.txt:
    #systemc_precomp_cim num_levels=... num_features=... dimension=...
    <level> <feature> <bitstring>

Bit d maps to word d >> 6, bit d & 63, matching hdc_systemc::hv_set_bit().
"""
from __future__ import annotations

import argparse
import pathlib
import re
from typing import Dict, List, Tuple


def parse_header(line: str) -> Dict[str, int]:
    values: Dict[str, int] = {}
    for key in ("num_levels", "num_features", "dimension"):
        match = re.search(rf"{key}=([0-9]+)", line)
        if not match:
            raise ValueError(f"missing {key} in CiM header")
        values[key] = int(match.group(1))
    return values


def bits_to_words(bits: str, word_bits: int) -> List[int]:
    if len(bits) % word_bits != 0:
        raise ValueError("dimension must be divisible by word_bits")
    words = [0 for _ in range(len(bits) // word_bits)]
    for d, char in enumerate(bits):
        if char == "1":
            words[d >> 6] |= 1 << (d & 63)
        elif char != "0":
            raise ValueError(f"invalid bit character {char!r}")
    return words


def read_cim(path: pathlib.Path, word_bits: int) -> Tuple[Dict[str, int], List[List[List[int]]]]:
    header = None
    entries: Dict[Tuple[int, int], List[int]] = {}

    with path.open("r", encoding="utf-8") as handle:
        for raw_line in handle:
            line = raw_line.strip()
            if not line:
                continue
            if line.startswith("#"):
                if "#systemc_precomp_cim" in line:
                    header = parse_header(line)
                continue
            if header is None:
                raise ValueError("CiM data found before header")

            parts = line.split()
            if len(parts) != 3:
                raise ValueError(f"invalid CiM data line: {line}")
            level = int(parts[0])
            feature = int(parts[1])
            bits = parts[2]
            if len(bits) != header["dimension"]:
                raise ValueError(f"bitstring length mismatch at level={level} feature={feature}")
            key = (level, feature)
            if key in entries:
                raise ValueError(f"duplicate CiM entry level={level} feature={feature}")
            entries[key] = bits_to_words(bits, word_bits)

    if header is None:
        raise ValueError("missing CiM header")

    num_levels = header["num_levels"]
    num_features = header["num_features"]
    dimension = header["dimension"]
    words = dimension // word_bits
    expected = num_levels * num_features
    if len(entries) != expected:
        raise ValueError(f"expected {expected} entries, got {len(entries)}")

    rom = []
    for level in range(num_levels):
        level_rows = []
        for feature in range(num_features):
            key = (level, feature)
            if key not in entries:
                raise ValueError(f"missing CiM entry level={level} feature={feature}")
            if len(entries[key]) != words:
                raise ValueError(f"word count mismatch at level={level} feature={feature}")
            level_rows.append(entries[key])
        rom.append(level_rows)
    return header, rom


def write_flat_header(output: pathlib.Path, input_path: pathlib.Path, symbol: str, header: Dict[str, int], rom: List[List[List[int]]]) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("w", encoding="utf-8", newline="\n") as out:
        out.write("// Generated by tools/generate_cim_rom.py.\n")
        out.write("// Source: " + input_path.as_posix() + "\n")
        out.write("// Do not edit by hand; regenerate from the CiM text export.\n")
        out.write("#ifndef SYSTEMC_HDC_GENERATED_CIM_ROM_DATASET00_H\n")
        out.write("#define SYSTEMC_HDC_GENERATED_CIM_ROM_DATASET00_H\n\n")
        out.write('#include "systemc_types.h"\n\n')
        out.write("namespace hdc_systemc {\n\n")
        out.write(f"static_assert(NUM_LEVELS == {header['num_levels']}, \"generated CiM num_levels mismatch\");\n")
        out.write(f"static_assert(NUM_FEATURES == {header['num_features']}, \"generated CiM num_features mismatch\");\n")
        out.write(f"static_assert(VECTOR_DIMENSION == {header['dimension']}, \"generated CiM dimension mismatch\");\n")
        out.write(f"static const hv_word_t {symbol}[NUM_LEVELS][NUM_FEATURES][HV_WORDS] = {{\n")
        for level_index, level_rows in enumerate(rom):
            out.write("    {\n")
            for feature_words in level_rows:
                words = ", ".join(f"hv_word_t(0x{word:016X}ULL)" for word in feature_words)
                out.write(f"        {{ {words} }},\n")
            out.write("    },")
            out.write(f" // level {level_index}\n")
        out.write("};\n\n")
        out.write("} // namespace hdc_systemc\n\n")
        out.write("#endif\n")


def write_word_banked_header(output: pathlib.Path, input_path: pathlib.Path, symbol: str, header: Dict[str, int], rom: List[List[List[int]]]) -> None:
    num_levels = header["num_levels"]
    num_features = header["num_features"]
    words = header["dimension"] // 64

    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("w", encoding="utf-8", newline="\n") as out:
        out.write("// Generated by tools/generate_cim_rom.py.\n")
        out.write("// Source: " + input_path.as_posix() + "\n")
        out.write("// Layout: one independent ROM per feature and hypervector word.\n")
        out.write("// Do not edit by hand; regenerate from the CiM text export.\n")
        out.write("#ifndef SYSTEMC_HDC_GENERATED_CIM_ROM_DATASET00_WORD_BANKED_H\n")
        out.write("#define SYSTEMC_HDC_GENERATED_CIM_ROM_DATASET00_WORD_BANKED_H\n\n")
        out.write('#include "systemc_types.h"\n\n')
        out.write("namespace hdc_systemc {\n\n")
        out.write(f"static_assert(NUM_LEVELS == {num_levels}, \"generated CiM num_levels mismatch\");\n")
        out.write(f"static_assert(NUM_FEATURES == {num_features}, \"generated CiM num_features mismatch\");\n")
        out.write(f"static_assert(VECTOR_DIMENSION == {header['dimension']}, \"generated CiM dimension mismatch\");\n")
        out.write(f"static_assert(HV_WORDS == {words}, \"generated CiM word count mismatch\");\n\n")

        for feature in range(num_features):
            for word in range(words):
                out.write(f"static const hv_word_t {symbol}_F{feature:02d}_W{word:02d}[NUM_LEVELS] = {{\n")
                for level in range(num_levels):
                    out.write(f"    hv_word_t(0x{rom[level][feature][word]:016X}ULL),")
                    out.write(f" // level {level}\n")
                out.write("};\n\n")

        out.write(f"inline hv_word_t {symbol}_WORD_BANKED_READ(unsigned feature, unsigned level, unsigned word) {{\n")
        out.write("    switch (feature) {\n")
        for feature in range(num_features):
            out.write(f"    case {feature}:\n")
            out.write("        switch (word) {\n")
            for word in range(words):
                out.write(f"        case {word}: return {symbol}_F{feature:02d}_W{word:02d}[level];\n")
            out.write(f"        default: return {symbol}_F{feature:02d}_W{words - 1:02d}[level];\n")
            out.write("        }\n")
        out.write("    default:\n")
        out.write("        switch (word) {\n")
        for word in range(words):
            out.write(f"        case {word}: return {symbol}_F{num_features - 1:02d}_W{word:02d}[level];\n")
        out.write(f"        default: return {symbol}_F{num_features - 1:02d}_W{words - 1:02d}[level];\n")
        out.write("        }\n")
        out.write("    }\n")
        out.write("}\n\n")
        out.write("} // namespace hdc_systemc\n\n")
        out.write("#endif\n")


def write_feature_banked_header(output: pathlib.Path, input_path: pathlib.Path, symbol: str, header: Dict[str, int], rom: List[List[List[int]]]) -> None:
    num_levels = header["num_levels"]
    num_features = header["num_features"]
    words = header["dimension"] // 64

    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("w", encoding="utf-8", newline="\n") as out:
        out.write("// Generated by tools/generate_cim_rom.py.\n")
        out.write("// Source: " + input_path.as_posix() + "\n")
        out.write("// Layout: one independent ROM per feature; each ROM stores level x word.\n")
        out.write("// Do not edit by hand; regenerate from the CiM text export.\n")
        out.write("#ifndef SYSTEMC_HDC_GENERATED_CIM_ROM_DATASET00_BANKED_H\n")
        out.write("#define SYSTEMC_HDC_GENERATED_CIM_ROM_DATASET00_BANKED_H\n\n")
        out.write('#include "systemc_types.h"\n\n')
        out.write("namespace hdc_systemc {\n\n")
        out.write(f"static_assert(NUM_LEVELS == {num_levels}, \"generated banked CiM num_levels mismatch\");\n")
        out.write(f"static_assert(NUM_FEATURES == {num_features}, \"generated banked CiM num_features mismatch\");\n")
        out.write(f"static_assert(VECTOR_DIMENSION == {header['dimension']}, \"generated banked CiM dimension mismatch\");\n")
        out.write(f"static_assert(HV_WORDS == {words}, \"generated banked CiM word count mismatch\");\n\n")

        for feature in range(num_features):
            out.write(f"static const hv_word_t {symbol}_F{feature:02d}[NUM_LEVELS][HV_WORDS] = {{\n")
            for level in range(num_levels):
                words_text = ", ".join(f"hv_word_t(0x{rom[level][feature][word]:016X}ULL)" for word in range(words))
                out.write(f"    {{ {words_text} }},")
                out.write(f" // level {level}\n")
            out.write("};\n\n")

        out.write("} // namespace hdc_systemc\n\n")
        out.write("#endif\n")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True, type=pathlib.Path)
    parser.add_argument("--output", required=True, type=pathlib.Path)
    parser.add_argument("--symbol", default="HDC_CIM_ROM_DATASET00")
    parser.add_argument("--layout", choices=("flat", "feature-banked", "word-banked"), default="flat")
    parser.add_argument("--word-bits", default=64, type=int)
    args = parser.parse_args()

    if args.word_bits != 64:
        raise ValueError("only 64-bit hypervector words are supported")

    header, rom = read_cim(args.input, args.word_bits)
    if args.layout == "word-banked":
        write_word_banked_header(args.output, args.input, args.symbol, header, rom)
    elif args.layout == "feature-banked":
        write_feature_banked_header(args.output, args.input, args.symbol, header, rom)
    else:
        write_flat_header(args.output, args.input, args.symbol, header, rom)


if __name__ == "__main__":
    main()
